[error] -- [E069] Naming Error: /Users/y3536zha/Desktop/scala_explicit_unsafe/scala_flexible_type_with_test_script/library/src/scala/IArray.scala:13:7 
[error] -- [E069] Naming Error: /Users/y3536zha/Desktop/scala_explicit_unsafe/scala_flexible_type_with_test_script/library/src/scala/IArray.scala:13:7 
[error] 13 |object IArray:
[error]    |       ^
[error]    |object IArray cannot have the same name as object IArray in package scala -- cannot define object member with the same name as a object member in self reference _.
[error]    |(Note: this can be resolved by using another name)
[error] 13 |object IArray:
[error]    |       ^
[error]    |object IArray cannot have the same name as object IArray in package scala -- cannot define object member with the same name as a object member in self reference _.
[error]    |(Note: this can be resolved by using another name)
[error] one error found
[error] one error found
[error] lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts: Error fetching artifacts:
[error] file:///Users/y3536zha/.ivy2/local/org.scala-lang/scala3-compiler_3/3.3.1-RC1-bin-SNAPSHOT/jars/scala3-compiler_3.jar: wrong checksum: /Users/y3536zha/.ivy2/local/org.scala-lang/scala3-compiler_3/3.3.1-RC1-bin-SNAPSHOT/jars/scala3-compiler_3.jar (expected SHA-1 7b2c019d401baee6c64c540f0d97e2ffdd28776f in /Users/y3536zha/.ivy2/local/org.scala-lang/scala3-compiler_3/3.3.1-RC1-bin-SNAPSHOT/jars/scala3-compiler_3.jar.sha1, got 7be5a8ab40f781955a91425a3d844c58cc842877)
[error] 
[error] 	at lmcoursier.internal.shaded.coursier.Artifacts$.$anonfun$fetchArtifacts$9(Artifacts.scala:365)
[error] 	at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$extension$1(Task.scala:14)
[error] 	at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$extension$1$adapted(Task.scala:14)
[error] 	at lmcoursier.internal.shaded.coursier.util.Task$.wrap(Task.scala:82)
[error] 	at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
[error] 	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
[error] 	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[error] 	at java.base/java.lang.Thread.run(Unknown Source)
[error] Caused by: lmcoursier.internal.shaded.coursier.cache.ArtifactError$WrongChecksum: wrong checksum: /Users/y3536zha/.ivy2/local/org.scala-lang/scala3-compiler_3/3.3.1-RC1-bin-SNAPSHOT/jars/scala3-compiler_3.jar (expected SHA-1 7b2c019d401baee6c64c540f0d97e2ffdd28776f in /Users/y3536zha/.ivy2/local/org.scala-lang/scala3-compiler_3/3.3.1-RC1-bin-SNAPSHOT/jars/scala3-compiler_3.jar.sha1, got 7be5a8ab40f781955a91425a3d844c58cc842877)
[error] 	at lmcoursier.internal.shaded.coursier.cache.FileCache.$anonfun$validateChecksum$4(FileCache.scala:142)
[error] 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[error] 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
[error] 	at scala.util.Success.map(Try.scala:213)
[error] 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[error] 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[error] 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[error] 	at java.base/java.lang.Thread.run(Unknown Source)
[error] (coreJVM / update) lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts: Error fetching artifacts:
[error] file:///Users/y3536zha/.ivy2/local/org.scala-lang/scala3-compiler_3/3.3.1-RC1-bin-SNAPSHOT/jars/scala3-compiler_3.jar: wrong checksum: /Users/y3536zha/.ivy2/local/org.scala-lang/scala3-compiler_3/3.3.1-RC1-bin-SNAPSHOT/jars/scala3-compiler_3.jar (expected SHA-1 7b2c019d401baee6c64c540f0d97e2ffdd28776f in /Users/y3536zha/.ivy2/local/org.scala-lang/scala3-compiler_3/3.3.1-RC1-bin-SNAPSHOT/jars/scala3-compiler_3.jar.sha1, got 7be5a8ab40f781955a91425a3d844c58cc842877)
[error] Total time: 2 s, completed Jun 14, 2023, 3:25:36 AM
[error] Test dotty.communitybuild.CommunityBuildTestB.discipline failed: java.lang.RuntimeException: Publish command exited with code 1 for project scalacheck. Project details:
[error] SbtCommunityProject(scalacheck,coreJVM/test;coreJS/test,List(),List(),dotty.communitybuild.SbtCommunityProject$$$Lambda$51/1130076828@351e8bf6,coreJVM/publishLocal;coreJS/publishLocal,null,List(-Xcheck-macros, -Ysafe-init, -Yexplicit-nulls, -language:unsafeNulls),false), took 43.355 sec
[error]     at dotty.communitybuild.CommunityProject.publish(projects.scala:64)
[error]     at dotty.communitybuild.CommunityProject.publish$(projects.scala:35)
[error]     at dotty.communitybuild.SbtCommunityProject.publish(projects.scala:104)
[error]     at dotty.communitybuild.CommunityBuildRunner$.run$$anonfun$1(CommunityBuildRunner.scala:24)
[error]     at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error]     at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error]     at scala.collection.immutable.List.foreach(List.scala:333)
[error]     at dotty.communitybuild.CommunityBuildRunner$.run(CommunityBuildRunner.scala:24)
[error]     at dotty.communitybuild.CommunityBuildTestB.discipline(CommunityBuildTest.scala:43)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[error]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[error]     at java.lang.reflect.Method.invoke(Unknown Source)
[error]     ...
[error] Failed: Total 1, Failed 1, Errors 0, Passed 0
[error] Failed tests:
[error] 	dotty.communitybuild.CommunityBuildTestB
[error] (community-build / Test / testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 108 s (01:48), completed Jun 14, 2023, 3:25:37 AM
